version: '3.8'
services:
  redis:
    image: redis:alpine
    restart: always
    environment:
      - TZ=Europe/Warsaw
    networks:
      - karkowka-network  
  postgres: 
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=karkowka
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_PASSWORD=postgresql
      - TZ=Europe/Warsaw
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - karkowka-network
  karkowka:
    build: ./backend
    restart: always
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresql
      - TZ=Europe/Warsaw
    networks:
      - karkowka-network
      - web-network
  web:
    build: ./web
    restart: always
    hostname: karkowka-web
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    networks:
      - web-network

networks:
  karkowka-network:
    driver: bridge
  web-network:
    driver: bridge